[package]
name = "a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "*"
serde_json = "*"
colored = "*"
reqwest = { version = "0.10.0-alpha.2", features = ["blocking"] }
